export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>AngularProject</title>
  <base href="https://github.com/Joshua-Mondie/angular-project.git">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">.container[_ngcontent-ng-c963648087]   ul[_ngcontent-ng-c963648087]{display:flex;justify-content:space-between;padding:2rem;background-color:gray}.container[_ngcontent-ng-c963648087]   li[_ngcontent-ng-c963648087]{list-style:none}.container[_ngcontent-ng-c963648087]   li[_ngcontent-ng-c963648087]   a[_ngcontent-ng-c963648087]{color:#fff;text-decoration:none;font-size:large}.routercontainer[_ngcontent-ng-c963648087]{display:flex;justify-content:center}</style><style ng-app-id="ng">.buttoncontainer[_ngcontent-ng-c1501112691]{padding:1rem}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="19.2.0" _nghost-ng-c963648087 ngh="1" ng-server-context="ssg"><nav _ngcontent-ng-c963648087 class="container"><ul _ngcontent-ng-c963648087><li _ngcontent-ng-c963648087><a _ngcontent-ng-c963648087 routerlink="home" href="https://github.com/Joshua-Mondie/angular-project.git/home" jsaction="click:;">Home</a></li><li _ngcontent-ng-c963648087><a _ngcontent-ng-c963648087 routerlink="contact" href="https://github.com/Joshua-Mondie/angular-project.git/contact" jsaction="click:;">Contact</a></li><li _ngcontent-ng-c963648087><a _ngcontent-ng-c963648087 routerlink="about" href="https://github.com/Joshua-Mondie/angular-project.git/about" jsaction="click:;">About</a></li></ul></nav><div _ngcontent-ng-c963648087 class="routercontainer"><router-outlet _ngcontent-ng-c963648087></router-outlet><app-about _nghost-ng-c1501112691 ngh="0"><p _ngcontent-ng-c1501112691>Welcome,This is the About Page</p><button _ngcontent-ng-c1501112691 routerlink="/home" class="buttoncontainer" tabindex="0" jsaction="click:;"> Navigate to the Home Page
</button></app-about><!----></div></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-IEDOJIUU.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"12":[{"i":"c1501112691","r":1}]}}]}</script></body></html>`;